version: '2'
services:
  wiremock:
    image: serrodcal/echo-wiremock
    build: ./wiremock
    volumes:
      - ./wiremock/mappings/echo.json:/home/wiremock/mappings/echo.json
      - ./wiremock/config/filebeat.yml:/etc/filebeat/filebeat.yml
    ports:
      - "8080:8080"
  esb:
    image: serrodcal/echo-wso2esb-5.0.0
    build: ./echoApp
    volumes:
      - ./echoApp/target/echoApp_1.0.0.car:/opt/wso2esb-5.0.0/repository/deployment/server/carbonapps/echoApp_1.0.0.car
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    depends_on:
      - wiremock
  elasticsearch:
    image: serrodcal/echo-elasticsearch
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - wiremock
      - esb
  logstash:
    image: serrodcal/echo-logstash
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - wiremock
      - esb
      - elasticsearch
  kibana:
    image: echo-kibana
    build: ./kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - wiremock
      - esb
      - elasticsearch
