version: '2'
services:
  wiremock:
    image: serrodcal/echo-wiremock
    build: ./wiremock
    volumes:
      - ./echoApp/target/echoApp_1.0.0.car:/opt/wso2esb-5.0.0/repository/deployment/server/carbonapps/echoApp_1.0.0.car
    ports:
      - "8080:8080"
    networks:
      - elk
  esb:
    image: serrodcal/echo-wso2esb-5.0.0
    build: ./echoApp
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    networks:
      - elk
    depends_on:
      - wiremock
  elasticsearch:
    image: serrodcal/echo-elasticsearch
    build: ./elasticsearch
    elasticsearch:
      build: elasticsearch/
      volumes:
        - ./wiremock/mappings/echo.json:/home/wiremock/mappings/echo.json
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk
      depends_on:
        - wiremock
        - esb
  logstash:
    image: serrodcal/echo-logstash
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - wiremock
      - esb
      - elasticsearch
  kibana:
    image: echo-kibana
    build: ./kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - wiremock
      - esb
      - elasticsearch
networks:
  elk:
    driver: bridge
