 ########################## Filebeat Configuration #############################
 
#=========================== Filebeat prospectors =============================
filebeat.prospectors:
- input_type: log
  paths: 
  - /opt/wso2esb-5.0.0/repository/logs/wso2carbon.log
  tags: [echo wso2] 
  fields_under_root: true
  fields:
    app: echo-wso2
    system: las 
  multiline.pattern: '^[[:space:]]+|^Caused by:' #
  multiline.negate: false
  multiline.match: after
 
# sensitive logs
- input_type: log
  paths:
  - /opt/wso2esb-5.0.0/repository/logs/sensitive/*.log
 tags: [echo, sensitive]
  fields_under_root: true
  fields:
    app: echo-sensitive
    system: las
  multiline.pattern: '^[[:space:]]+|^Caused by:'
  multiline.negate: false
  multiline.match: after
 
# obfuscated logs
- input_type: log
  paths:
  - /opt/wso2esb-5.0.0/repository/logs/obfuscated/*.log
  tags: [echo, obfuscated]
  fields_under_root: true
  fields:
    app: echo-obfuscated
    system: las
  multiline.pattern: '^[[:space:]]+|^Caused by:'
  multiline.negate: false
  multiline.match: after
 
#========================= Filebeat global options ============================
  registry_file: /var/lib/filebeat/registry
 
#================================ Outputs =====================================
 
#----------------------------- Logstash output --------------------------------
output.logstash: 
  hosts:
  - logstash:5000 
  loadbalance: false
 
#================================ Logging =====================================
 
# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 10